# Generated by Django 2.0.5 on 2018-06-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Sitio web', 'Sitio web'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Google+', 'Google+'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Flickr', 'Flickr'), ('Pinterest', 'Pinterest'), ('Vimeo', 'Vimeo'), ('Otra', 'Otra')], max_length=25)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
        migrations.RemoveField(
            model_name='contraparte',
            name='rss',
        ),
        migrations.RemoveField(
            model_name='contraparte',
            name='sitio_web',
        ),
        migrations.AddField(
            model_name='redes',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contrapartes.Contraparte'),
        ),
    ]
