# Generated by Django 2.0.5 on 2018-07-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0003_auto_20180702_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraparte',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
