# Generated by Django 2.0.5 on 2018-07-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0004_contraparte_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajero',
            name='user',
            field=models.ManyToManyField(related_name='Destinatarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajero',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
