# Generated by Django 2.0.5 on 2020-10-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrapartes', '0005_auto_20180704_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrapartes.Pais')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
