# Generated by Django 2.0.5 on 2018-06-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', sorl.thumbnail.fields.ImageField(upload_to='galerias/')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Temas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galería imagenes',
                'verbose_name_plural': 'Galerías imagenes',
            },
        ),
        migrations.CreateModel(
            name='GaleriaVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Temas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galería videos',
                'verbose_name_plural': 'Galerías videos',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='galerias/')),
                ('imagenes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galerias.GaleriaImagenes')),
            ],
        ),
    ]
