# Generated by Django 3.2 on 2023-07-15 15:54

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', sorl.thumbnail.fields.ImageField(upload_to='galerias/')),
            ],
            options={
                'verbose_name': 'Galería imagenes',
                'verbose_name_plural': 'Galerías imagenes',
            },
        ),
        migrations.CreateModel(
            name='GaleriaVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'Galería videos',
                'verbose_name_plural': 'Galerías videos',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='galerias/')),
                ('imagenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerias.galeriaimagenes')),
            ],
        ),
    ]
