# Generated by Django 2.0.5 on 2018-06-20 14:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='galeriavideos',
            name='portada',
        ),
        migrations.AddField(
            model_name='galeriavideos',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
