# Generated by Django 2.0.5 on 2018-06-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='imagen',
            new_name='url',
        ),
    ]
