# Generated by Django 2.0.5 on 2018-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_auto_20180814_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
