# Generated by Django 2.0.5 on 2018-06-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0002_auto_20180605_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaimagenes',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Temas'),
        ),
        migrations.AlterField(
            model_name='galeriavideos',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Temas'),
        ),
        migrations.DeleteModel(
            name='Tematica',
        ),
    ]
