# Generated by Django 2.0.5 on 2018-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerias', '0003_auto_20180820_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(max_length=90),
        ),
    ]
