# Generated by Django 3.2 on 2023-07-15 15:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrapartes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('precio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Precio y unidad de medida')),
                ('precio_del_dia', models.BooleanField(verbose_name='Mostrar texto "Consulte precio del día"')),
                ('foto_principal', sorl.thumbnail.fields.ImageField(upload_to='productos/')),
                ('disponible', models.BooleanField()),
                ('publicada', models.BooleanField()),
                ('enviar_correo', models.BooleanField()),
                ('correo_enviado', models.BooleanField(editable=False)),
                ('contacto_1', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_2', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=200, null=True)),
                ('vistas', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('localizacion', models.ManyToManyField(to='contrapartes.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Servicio de Producto',
                'verbose_name_plural': 'Servicios de Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.CreateModel(
            name='RedesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Sitio web', 'Sitio web'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Google+', 'Google+'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Flickr', 'Flickr'), ('Pinterest', 'Pinterest'), ('Vimeo', 'Vimeo'), ('Otra', 'Otra')], max_length=25)),
                ('url', models.URLField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
            },
        ),
        migrations.CreateModel(
            name='Propuesta_valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Propuesta de valor',
                'verbose_name_plural': 'Propuesta de valor',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ManyToManyField(blank=True, to='catalogo.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_servicio',
            field=models.ManyToManyField(blank=True, to='catalogo.ServiciosProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FotosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='ArchivosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='producto/archivos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
