# Generated by Django 2.0.5 on 2020-10-19 15:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrapartes', '0006_departamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='producto/archivos/')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='FotosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('precio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Precio y unidad de medida')),
                ('foto_principal', sorl.thumbnail.fields.ImageField(upload_to='productos/')),
                ('disponible', models.BooleanField()),
                ('vistas', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('localizacion', models.ManyToManyField(to='contrapartes.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta_valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Producto')),
            ],
            options={
                'verbose_name': 'Propuesta de valor',
                'verbose_name_plural': 'Propuesta de valor',
            },
        ),
        migrations.CreateModel(
            name='ServiciosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Servicio de Producto',
                'verbose_name_plural': 'Servicios de Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ManyToManyField(to='catalogo.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_servicio',
            field=models.ManyToManyField(to='catalogo.ServiciosProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotosproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Producto'),
        ),
        migrations.AddField(
            model_name='archivosproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.Producto'),
        ),
    ]
