# Generated by Django 2.0.5 on 2020-10-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201030_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='correo_enviado',
            field=models.BooleanField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
