# Generated by Django 2.0.5 on 2020-12-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20201204_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redes',
            new_name='RedesProducto',
        ),
    ]
