# Generated by Django 2.0.5 on 2020-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201209_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_del_dia',
            field=models.BooleanField(default=0, verbose_name='Mostrar texto "Consulte precio del día"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivosproducto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='producto/archivos/'),
        ),
        migrations.AlterField(
            model_name='archivosproducto',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
