# Generated by Django 3.2 on 2023-07-15 15:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='biblioteca/img/')),
                ('autor', models.CharField(max_length=250)),
                ('editorial', models.CharField(max_length=250)),
                ('lugar', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('isbn', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_paginas', models.IntegerField()),
                ('resumen', ckeditor_uploader.fields.RichTextUploadingField()),
                ('archivo', models.FileField(upload_to='biblioteca/archivos/')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='biblioteca.categoria')),
            ],
            options={
                'verbose_name_plural': 'Archivos',
            },
        ),
    ]
