# Generated by Django 2.0.5 on 2018-06-28 23:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='autor',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='editorial',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='isbn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='archivos',
            name='lugar',
            field=models.CharField(default=django.utils.datetime_safe.date.today, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='numero_paginas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='resumen',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivos',
            name='slug',
            field=models.SlugField(default=django.utils.datetime_safe.date.today, editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
