# Generated by Django 2.0.5 on 2018-06-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
        ('biblioteca', '0002_auto_20180628_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='tematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Temas'),
            preserve_default=False,
        ),
    ]
