# Generated by Django 2.0.5 on 2018-06-07 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
            },
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='opinion/')),
                ('opinion', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)])),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opiniones.Ocupacion')),
            ],
            options={
                'verbose_name': 'Opinión',
                'verbose_name_plural': 'Opiniones',
            },
        ),
    ]
