# Generated by Django 2.0.5 on 2018-06-27 17:34

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerProposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(help_text='720x440', upload_to='banner-proposito/')),
            ],
            options={
                'verbose_name': 'Banner proposito',
                'verbose_name_plural': 'Banner proposito',
            },
        ),
    ]
