# Generated by Django 2.0.5 on 2018-06-27 18:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_bannerproposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerproposito',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(help_text='340x180', upload_to='banner-proposito/'),
        ),
    ]
