# Generated by Django 2.0.5 on 2018-05-10 17:37

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioNotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime(2018, 5, 10, 17, 37, 1, 313394))),
                ('comentario', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('fecha', models.DateField(default=datetime.datetime(2018, 5, 10, 17, 37, 1, 299587), verbose_name='Fecha de publicación')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='comentarionotas',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notas.Notas'),
        ),
        migrations.AddField(
            model_name='comentarionotas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
