# Generated by Django 2.0.5 on 2018-05-10 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarionotas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 17, 42, 45, 732098)),
        ),
        migrations.AlterField(
            model_name='notas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 17, 42, 45, 719409), verbose_name='Fecha de publicación'),
        ),
    ]
