# Generated by Django 2.0.5 on 2019-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='publicada',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
