# Generated by Django 2.0.5 on 2018-05-10 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_auto_20180510_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarionotas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 21, 1, 47, 964114)),
        ),
        migrations.AlterField(
            model_name='notas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 21, 1, 47, 963358), verbose_name='Fecha de publicación'),
        ),
    ]
