# Generated by Django 2.0.5 on 2019-11-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_notas_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='correo_enviado',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
