# Generated by Django 2.0.5 on 2018-05-21 17:47

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20180510_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='notas/'),
        ),
        migrations.AlterField(
            model_name='comentarionotas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='notas',
            name='slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
