# Generated by Django 2.0.5 on 2018-05-22 15:15

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('notas', '0004_auto_20180521_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Separar elementos con "," ', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
