# Generated by Django 2.0.5 on 2018-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_notas_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='vistas',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
