# Generated by Django 2.0.5 on 2018-05-28 20:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_auto_20180528_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AlterField(
            model_name='notas',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video (url)'),
        ),
        migrations.AddField(
            model_name='notas',
            name='temas',
            field=models.ManyToManyField(to='notas.Temas'),
        ),
    ]
