# Generated by Django 2.0.5 on 2018-05-10 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportes',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 21, 1, 47, 961829)),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 21, 1, 47, 962687)),
        ),
        migrations.AlterField(
            model_name='foros',
            name='creacion',
            field=models.DateField(default=datetime.datetime(2018, 5, 10, 21, 1, 47, 949717)),
        ),
    ]
