# Generated by Django 2.0.5 on 2018-05-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foros', '0002_auto_20180510_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportes',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foros',
            name='creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
