# Generated by Django 3.2 on 2023-07-15 15:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('banner', sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x500', null=True, upload_to='informes/banner/')),
                ('objectivos', ckeditor_uploader.fields.RichTextUploadingField()),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('imagen_descripcion', sorl.thumbnail.fields.ImageField(blank=True, help_text='800x600', null=True, upload_to='informes/img-descripcion/')),
                ('coordinador_proyecto', models.CharField(max_length=300, verbose_name='Coordinador general del proyecto')),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=50)),
                ('responsable_proyecto', models.CharField(max_length=300)),
                ('slug', models.SlugField(editable=False, max_length=320)),
                ('url_para_compartir', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RangoFechaImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
            options={
                'verbose_name': 'Fecha Imágen',
                'verbose_name_plural': 'Fecha Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='informes/monitoreo/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('tipo_reporte', models.CharField(choices=[('Informe técnico', 'Informe técnico'), ('Informe financiero', 'Informe financiero')], max_length=50)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('fecha_informe', models.DateField()),
                ('archivo', models.FileField(upload_to='informes/informe/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('archivo', sorl.thumbnail.fields.ImageField(upload_to='informes/imgenes/')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.rangofechaimagenes')),
            ],
            options={
                'verbose_name': 'Imágen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.CreateModel(
            name='HistoriasExito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='informes/historias-exito/')),
                ('texto', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
            options={
                'verbose_name': 'Historia de éxito',
                'verbose_name_plural': 'Historias de éxito',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='informes/imgenes/')),
                ('archivo', models.FileField(upload_to='informes/documentos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosMonitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='informes/monitoreo/')),
                ('monitoreo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.monitoreo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='informes/archivos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proyecto')),
            ],
            options={
                'verbose_name': 'Archivo proyecto',
                'verbose_name_plural': 'Archivos proyecto',
            },
        ),
    ]
