# Generated by Django 2.0.5 on 2019-11-11 15:41

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('imagen', sorl.thumbnail.fields.ImageField(upload_to='informes/imgenes/')),
                ('archivo', models.FileField(upload_to='informes/documentos/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.Proyecto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'Archivo proyecto', 'verbose_name_plural': 'Archivos proyecto'},
        ),
    ]
