# Generated by Django 2.0.5 on 2019-11-11 16:03

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_auto_20191111_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosMonitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='informes/monitoreo/')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='informes/monitoreo/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.Proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='documento',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='informes/imgenes/'),
        ),
        migrations.AddField(
            model_name='archivosmonitoreo',
            name='monitoreo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.Monitoreo'),
        ),
    ]
