# Generated by Django 2.0.5 on 2019-12-04 16:57

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_auto_20191111_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoFechaImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Fecha Imágen',
                'verbose_name_plural': 'Fecha Imágenes',
            },
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='proyecto',
        ),
        migrations.AlterModelOptions(
            name='archivosmonitoreo',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='banner',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='1350x500', null=True, upload_to='informes/banner/'),
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
        migrations.AddField(
            model_name='rangofechaimagenes',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.Proyecto'),
        ),
    ]
