# Generated by Django 2.0.5 on 2019-12-04 17:00

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_auto_20191204_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('archivo', sorl.thumbnail.fields.ImageField(upload_to='informes/imgenes/')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.RangoFechaImagenes')),
            ],
            options={
                'verbose_name': 'Imágen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
    ]
