# Generated by Django 2.0.5 on 2019-12-04 20:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0005_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen_descripcion',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='800x600', null=True, upload_to='informes/img-descripcion/'),
        ),
    ]
