# Generated by Django 2.0.5 on 2020-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0006_proyecto_imagen_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='nombre',
            field=models.CharField(default='Nombre del archivo', max_length=300),
            preserve_default=False,
        ),
    ]
