# Generated by Django 2.0.5 on 2018-05-23 20:14

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='publicaciones/img/')),
                ('archivo', models.FileField(upload_to='publicaciones/archivos/')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
