# Generated by Django 3.2 on 2023-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='correo_enviado',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
