# Generated by Django 2.0.5 on 2018-08-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_auto_20180823_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=250),
            preserve_default=False,
        ),
    ]
