# Generated by Django 2.0.5 on 2018-08-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_auto_20180823_0825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='ArchivosPublicacion',
        ),
        migrations.RenameModel(
            old_name='Audios',
            new_name='AudiosPublicacion',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='VideosPublicacion',
        ),
    ]
