# Generated by Django 2.0.5 on 2019-11-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_auto_20191106_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='publicada',
            field=models.BooleanField(),
        ),
    ]
