# Generated by Django 2.0.5 on 2020-10-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_auto_20201019_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Información',
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publicaciones.Herramientas'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='informacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='publicaciones.Informacion'),
        ),
    ]
