# Generated by Django 2.0.5 on 2020-10-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_auto_20201026_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramientas',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='informacion',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
