# Generated by Django 2.0.5 on 2020-10-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_auto_20201026_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Biblioteca', 'verbose_name_plural': 'Biblioteca'},
        ),
    ]
