# Generated by Django 2.0.5 on 2018-06-15 15:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('lugar', models.CharField(max_length=250)),
                ('publico', models.BooleanField()),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
