# Generated by Django 3.2 on 2023-07-15 15:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('final', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('lugar', models.CharField(max_length=250)),
                ('publico', models.BooleanField()),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('correo_enviado', models.BooleanField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=200, verbose_name='Nombre')),
                ('adjunto', models.FileField(upload_to=utils.get_file_path, verbose_name='Adjunto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agendas')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('descripcion', models.CharField(max_length=600)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.agendas')),
            ],
        ),
    ]
