# Generated by Django 2.0.5 on 2018-05-10 21:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField()),
                ('inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('final', models.DateField(verbose_name='Fecha de Finalización')),
                ('publico', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agendas',
            },
        ),
    ]
