# Generated by Django 2.0.5 on 2018-06-27 19:14

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agendaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=200, verbose_name='Nombre')),
                ('adjunto', models.FileField(upload_to=utils.get_file_path, verbose_name='Adjunto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendas.Agendas')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
