# Generated by Django 2.0.5 on 2018-05-22 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agendas_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendas',
            name='final',
        ),
        migrations.AddField(
            model_name='agendas',
            name='hora_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendas',
            name='lugar',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
