# Generated by Django 2.0.5 on 2018-07-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_documentosevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.Agendas'),
        ),
        migrations.AlterField(
            model_name='documentosevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.Agendas'),
        ),
    ]
