# Generated by Django 2.0.5 on 2018-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_auto_20180522_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendas',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora fin'),
        ),
        migrations.AlterField(
            model_name='agendas',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora inicio'),
        ),
    ]
