# Generated by Django 2.0.5 on 2018-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_auto_20180702_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
    ]
