# Generated by Django 2.0.5 on 2018-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0004_auto_20180522_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
