# Generated by Django 2.0.5 on 2018-08-14 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0005_agendas_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
