# Generated by Django 2.0.5 on 2019-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0006_agendaevento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendas',
            name='correo_enviado',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
